In [ ]:
import pandas as pd

In [ ]:
data = {
    "age" : [25,30,35],
    "city": ['kathmandu','butwal','pokhara']
}

In [ ]:
df = pd.DataFrame(data,index = ['ram','shyam','hari'])

In [ ]:
df

       age       city
ram     25  kathmandu
shyam   30     butwal
hari    35    pokhara

In [ ]:
df.loc['shyam']

# using .loc : target the row by its string label

age         30
city    butwal
Name: shyam, dtype: object

In [ ]:
df.iloc[1]

age         30
city    butwal
Name: shyam, dtype: object

In [ ]:
#slicing multiple rows

df.loc['ram':'hari']

       age       city
ram     25  kathmandu
shyam   30     butwal
hari    35    pokhara

In [ ]:
df.loc['ram':'shyam']

       age       city
ram     25  kathmandu
shyam   30     butwal

In [ ]:
df.iloc[0:1]

     age       city
ram   25  kathmandu

In [ ]:
#row and column selection combined
#.loc : specify row and column labels directly

df.loc['ram','city']

'kathmandu'

In [ ]:
df.loc['ram','age']

np.int64(25)

In [ ]:
# using .iloc : use integer indices for both dimensions.
df.iloc[0,1]

'kathmandu'

In [ ]:
df.iloc[1,1]

'butwal'

#Exploration

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
titanic_df = pd.read_csv('/content/drive/MyDrive/data file/titanic-data.csv')

In [ ]:
titanic_df.shape

(891, 12)

In [ ]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [ ]:
titanic_df[['Age','Fare']].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [ ]:
titanic_df[['Age','Fare']].max()

Age      80.0000
Fare    512.3292
dtype: float64

In [ ]:
titanic_df[['Age','Fare']].min()

Age     0.42
Fare    0.00
dtype: float64

In [ ]:
titanic_df[['Age','Fare']].std()

Age     14.526497
Fare    49.693429
dtype: float64

In [ ]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
titanic_df.value_counts("Survived")

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
titanic_df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Sex","Survived"], ascending=True)

Sex     Survived
female  0            81
male    1           109
female  1           233
male    0           468
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Sex","Survived"],normalize = True, ascending=True)

Sex     Survived
female  0           0.090909
male    1           0.122334
female  1           0.261504
male    0           0.525253
Name: proportion, dtype: float64

In [ ]:
titanic_df.value_counts(["Pclass","Survived"], ascending=True)

Pclass  Survived
1       0            80
2       1            87
        0            97
3       1           119
1       1           136
3       0           372
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df["Sex"] == "male"].value_counts(["Pclass", "Survived"])

Pclass  Survived
3       0           300
2       0            91
1       0            77
3       1            47
1       1            45
2       1            17
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df["Sex"] == "female"].value_counts(["Survived"])

Survived
1           233
0            81
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Age","Survived"], ascending=True)

Age    Survived
0.42   1            1
0.67   1            1
0.92   1            1
3.00   0            1
6.00   0            1
                   ..
22.00  0           16
25.00  0           17
18.00  0           17
28.00  0           18
21.00  0           19
Name: count, Length: 142, dtype: int64

In [ ]:
titanic_df.value_counts(["Fare","Survived"], ascending=True)

Fare      Survived
247.5208  1            1
0.0000    1            1
4.0125    0            1
5.0000    0            1
6.2375    0            1
                      ..
13.0000   1           16
7.7500    0           22
13.0000   0           26
7.8958    0           37
8.0500    0           38
Name: count, Length: 330, dtype: int64

In [ ]:
titanic_df.value_counts(["Embarked","Survived"], ascending=True)

Embarked  Survived
Q         1            30
          0            47
C         0            75
          1            93
S         1           217
          0           427
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Parch","Survived"], ascending=True)

Parch  Survived
5      1             1
6      0             1
3      0             2
       1             3
4      0             4
5      0             4
2      0            40
       1            40
1      0            53
       1            65
0      1           233
       0           445
Name: count, dtype: int64

### 1. Survived Passengers by Gender

In [ ]:
survived_df = titanic_df[titanic_df['Survived'] == 1].copy()

In [ ]:
print(survived_df['Sex'].value_counts())

Sex
female    233
male      109
Name: count, dtype: int64

### 2. Survived Passengers by Pclass

In [ ]:
print(survived_df['Pclass'].value_counts())

Pclass
1    136
3    119
2     87
Name: count, dtype: int64

### 3. Survived Passengers by Age Group

In [ ]:
# Create age groups
age_bins = [0, 12, 18, 60, titanic_df['Age'].max()]
age_labels = ['Child', 'Teenager', 'Adult', 'Senior']
survived_df['AgeGroup'] = pd.cut(survived_df['Age'], bins=age_bins, labels=age_labels, right=False)

print(survived_df['AgeGroup'].value_counts())

AgeGroup
Adult       222
Child        39
Teenager     22
Senior        6
Name: count, dtype: int64

### 4. Survived Passengers by Fare Group

In [ ]:
fare_bins = [0, 10, 30, 100]
fare_labels = ['very low', 'low', 'high']

survived_df['FareGroup'] = pd.cut(
    survived_df['Fare'],
    bins=fare_bins,
    labels=fare_labels,
    right=False
)

print(survived_df['FareGroup'].value_counts())

FareGroup
low         134
high        102
very low     67
Name: count, dtype: int64